FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY yarn.lock    ./
COPY tsconfig*.json ./
COPY src src

RUN yarn install --frozen-lockfile
RUN yarn build

FROM node:16-alpine
ENV NODE_ENV=production
RUN apk add --no-cache tini
WORKDIR /app
RUN chown node:node .
USER node
COPY package.json ./
COPY yarn.lock    ./
COPY .env ./
COPY build ./build

RUN yarn install

COPY --from=builder /app/lib/ lib/

EXPOSE 8080

ENTRYPOINT [ "/sbin/tini","--", "node", "lib/index.js" ]